import random
import string


class MessageGenerator:
    def __init__(self):
        self.generic_messages = [
            "Hey there! Just wanted to drop a quick message to say hi and see how you're doing. Hope you're having a great day! 😊",
            "Hi friend! Sending some positive vibes your way. Hope you're doing well!",
            "Hey buddy! Remember, you're awesome and capable of achieving anything you set your mind to! 💪",
            "Hello! Just checking in to see how you're doing. Let me know if there's anything I can do to support you!",
            "Hi! Wishing you a fantastic day filled with joy and laughter. Keep shining bright! ✨",
            "Hey! Hope your day is as amazing as you are! 😄",
            "Hi there! Just wanted to remind you that you're appreciated and valued. Keep being awesome!",
            "Hey friend! Just dropping by to say hello and spread some positivity your way. Have a wonderful day!",
            "Hello! Sending you lots of love and good vibes. You've got this!",
            "Hi! Remember, every challenge you face is an opportunity to grow stronger. Keep pushing forward!",
            "Hey there! Just wanted to send a quick virtual hug your way. You're not alone, and I'm here for you!",
            "Hi friend! Hope your day is filled with laughter, love, and all the good things in life. You deserve it!"
        ]
        
        self.messages_hacker = [
            "Initiating secure connection. Your digital presence is attracting attention. Stay vigilant. - ShadowCipher",
            "Warning: Unusual activity detected in your online behavior. Exercise caution. - DarkNetOp",
            "Cipher protocol activated. Your online actions have drawn scrutiny. Maintain discretion. - GhostHacker",
            "Alert: Anomaly detected in network traffic. You may be under surveillance. - StealthByte",
            "Security breach alert: Your digital footprint is being monitored. Take evasive action. - PhantomByte",
            "Caution: Digital surveillance detected. Your activities are being watched closely. - CyberPhantom",
            "Intrusion warning: Your online presence is under scrutiny. Stay under the radar. - CryptoGhost",
            "Encryption compromised. Your digital identity may be at risk. Take precautions. - ShadowCipher",
            "Attention: Suspicious network activity detected. Exercise heightened security measures. - DarkNetOp",
            "Security protocol breached. Your digital security may have been compromised. - GhostHacker",
            "Warning: Abnormal data flow detected in your network. Stay alert. - StealthByte",
            "Code red: Unauthorized access detected. Your online security is under threat. - PhantomByte",
            "Initiating secure transmission. Your digital activities have attracted attention. Stay covert. - CyberPhantom",
            "Caution: Anomalies detected in network traffic. Proceed with caution. - CryptoGhost",
            "Alert: Cipher protocol engaged. Your online presence may be compromised. - ShadowCipher",
            "Security breach detected. Your digital identity is vulnerable. Take action. - DarkNetOp",
            "Warning: Digital surveillance in progress. Maintain operational security. - GhostHacker",
            "Attention: Unusual patterns detected in your online behavior. Stay under the radar. - StealthByte",
            "Intrusion alert: Your online activities are being monitored. Stay low-key. - PhantomByte",
            "Encryption compromised. Your digital security may be compromised. Take evasive action. - CyberPhantom",
            "Alert: Suspicious network activity detected. Exercise caution in your online interactions. - CryptoGhost",
            "Security protocol breached. Your digital footprint is attracting unwanted attention. - ShadowCipher",
            "Code red: Unauthorized access detected. Take measures to protect your online security. - DarkNetOp",
            "Initiating secure communication. Your digital presence is under scrutiny. Maintain discretion. - GhostHacker",
            "Caution: Abnormal data flow detected. Your online activities may be compromised. - StealthByte",
            "Alert: Cipher protocol activated. Your digital security is at risk. Take precautions. - PhantomByte",
            "Security breach detected. Your digital privacy may be compromised. Take evasive action. - CyberPhantom",
            "Warning: Digital surveillance detected. Exercise caution in your online interactions. - CryptoGhost",
            "Attention: Unusual activity detected in your network. Stay alert. - ShadowCipher",
            "Intrusion warning: Your digital footprint has been noticed. Stay under the radar. - DarkNetOp",
            "Encryption compromised. Your online security may be compromised. Take action. - GhostHacker",
            "Alert: Suspicious network activity detected. Proceed with caution in your online activities. - StealthByte",
            "Security protocol breached. Your digital identity is vulnerable. Take evasive action. - PhantomByte",
            "Code red: Unauthorized access detected. Exercise caution in your digital interactions. - CyberPhantom",
            "Initiating secure transmission. Your digital presence is under surveillance. Stay covert. - CryptoGhost",
            "Caution: Anomalies detected in network traffic. Maintain operational security. - ShadowCipher",
            "Alert: Cipher protocol engaged. Your digital privacy may be compromised. - DarkNetOp",
            "Security breach detected. Your online activities are being monitored. Take action. - GhostHacker",
            "Warning: Digital surveillance in progress. Stay low-key in your online interactions. - StealthByte",
            "Attention: Unusual patterns detected in your online behavior. Exercise caution. - PhantomByte",
            "Intrusion alert: Your digital security may be compromised. Stay vigilant. - CyberPhantom",
            "Warning: Data integrity at risk. Immediate attention required to safeguard digital assets. - CyberSentinel",
            "Caution: Encryption anomaly detected. Verify security protocols immediately. - NetShield",
            "Alert: Unauthorized data access suspected. Increase security measures now. - GuardByte",
            "Notice: Potential compromise in system integrity. Review all network activity. - SecurePath",
            "Urgent: Suspicious encryption behavior observed. Tighten security controls. - CryptoWatch",
            "Warning: Network perimeter breach detected. Activate enhanced defensive measures. - FirewallGuard",
            "Alert: Possible phishing attempt in progress. Do not disclose personal information. - PhishNet",
            "Security Notice: Irregular access patterns observed. Confirm user identities. - IdentityShield",
            "Critical: Vulnerable software detected. Update systems to prevent potential breaches. - PatchMaster",
            "Attention: Elevated risk of cyber intrusion detected. Secure all digital communications. - NetSecure",
            "Warning: Malicious code detected in network stream. Initiate malware scans. - VirusSweeper",
            "Alert: System integrity compromised. Initiate recovery protocols immediately. - RecoveryOps",
            "Security Update: Anomaly in authentication logs. Review all recent sessions. - AccessGuard",
            "Notice: Increased risk of data exfiltration detected. Monitor all outbound traffic. - DataWatch",
            "Urgent: Threat to digital infrastructure imminent. Prioritize cybersecurity measures. - CyberDefender",
            "Warning: Abnormal network behavior detected. Assess potential security threats. - ThreatAnalyzer",
            "Alert: High-risk vulnerability found. Patch systems immediately to avoid exploitation. - SecurePatch",
            "Security Advisory: Unauthorized attempts to access secure files detected. Enhance file security. - FileGuard",
            "Critical Warning: Network infrastructure under attack. Deploy countermeasures. - NetworkDefender",
            "Alert: Disruption in encryption channels observed. Assess for potential data breaches. - EncryptGuard",
            "Caution: Irregular data transmissions detected. Assess for potential interception. - SignalCrypt",
            "Warning: Unusual login attempts from unrecognized locations. Verify account security. - LoginMonitor",
            "Alert: Network defense parameters altered. Revert to secure configurations. - DefenseGuard",
            "Security Notice: Suspicious registry modifications detected. Conduct system audits. - SystemCheck",
            "Urgent: Elevated activity in admin panels observed. Confirm authenticity of sessions. - AdminWatch",
            "Notice: Possible intrusion in secure zones. Initiate lockdown procedures. - ZoneDefender",
            "Alert: High-risk IP addresses connected to network. Block suspicious connections. - IPBlocker",
            "Caution: Data leakage suspected. Secure confidential information immediately. - LeakPrevent",
            "Warning: External devices attempting unauthorized connections. Monitor and control access. - DeviceShield",
            "Critical: Unusual outbound traffic patterns observed. Investigate for data theft. - TrafficGuard",
            "Security Advisory: Multiple failed attempts to access secure data detected. Increase alertness. - FailSafe",
            "Alert: Encryption keys potentially compromised. Reissue new keys promptly. - KeyMaster",
            "Notice: Cloud storage irregularities reported. Verify integrity of stored data. - CloudSecure",
            "Urgent: Anomalies in system performance detected. Check for hidden processes. - PerformanceCheck",
            "Warning: Unauthorized changes to firewall settings detected. Restore to known safe state. - FirewallRestore",
            "Security Update: Suspicious API calls observed. Validate against external threats. - APIMonitor",
            "Critical Alert: Possible zero-day vulnerability exploited. Apply emergency patches. - ZeroDayDefense",
            "Alert: Increased DNS requests suggest possible DDoS attack. Prepare defenses. - DNSProtect",
            "Warning: Unverified scripts running on system. Investigate origin and purpose. - ScriptScanner",
            "Caution: Network access points open to vulnerabilities. Conduct comprehensive security sweep. - AccessPointCheck"
        ]

    def generate_message(self):
        if random.random() < 1:
            return random.choice(self.messages_hacker)
        else:
            return random.choice(self.generic_messages)
        

class GameSlugGenerator:
    def __init__(self):
        self.game_slugs = [
            "",  
            "confessions",  
            "3words",  
            "tbh",  
            "shipme",  
            "yourcrush",  
            "cancelled",  
            "dealbreaker"  
        ]
        
    def generate_game_slug(self):
        return random.choice(self.game_slugs)
    


class DeviceIDGenerator:
    '''
    Generates device ID for the request.
    '''
    @staticmethod
    def generate_device_id():
        return '-'.join([''.join(random.choices(string.ascii_lowercase + string.digits, k=part_length))
                         for part_length in [8, 4, 4, 4, 12]])
        

class UserRegionGenerator:
    countries = {
        "AF": "Afghanistan",
        "AL": "Albania",
        "DZ": "Algeria",
        "AS": "American Samoa",
        "AD": "Andorra",
        "AO": "Angola",
        "AI": "Anguilla",
        "AQ": "Antarctica",
        "AG": "Antigua and Barbuda",
        "AR": "Argentina",
        "AM": "Armenia",
        "AW": "Aruba",
        "AU": "Australia",
        "AT": "Austria",
        "AZ": "Azerbaijan",
        "BS": "Bahamas",
        "BH": "Bahrain",
        "BD": "Bangladesh",
        "BB": "Barbados",
        "BY": "Belarus",
        "BE": "Belgium",
        "BZ": "Belize",
        "BJ": "Benin",
        "BM": "Bermuda",
        "BT": "Bhutan",
        "BO": "Bolivia",
        "BA": "Bosnia and Herzegovina",
        "BW": "Botswana",
        "BV": "Bouvet Island",
        "BR": "Brazil",
        "IO": "British Indian Ocean Territory",
        "BN": "Brunei Darussalam",
        "BG": "Bulgaria",
        "BF": "Burkina Faso",
        "BI": "Burundi",
        "CV": "Cabo Verde",
        "KH": "Cambodia",
        "CM": "Cameroon",
        "CA": "Canada",
        "KY": "Cayman Islands",
        "CF": "Central African Republic",
        "TD": "Chad",
        "CL": "Chile",
        "CN": "China",
        "CX": "Christmas Island",
        "CC": "Cocos (Keeling) Islands",
        "CO": "Colombia",
        "KM": "Comoros",
        "CG": "Congo",
        "CD": "Congo (DRC)",
        "CK": "Cook Islands",
        "CR": "Costa Rica",
        "CI": "Côte d'Ivoire",
        "HR": "Croatia",
        "CU": "Cuba",
        "CW": "Curaçao",
        "CY": "Cyprus",
        "CZ": "Czechia",
        "DK": "Denmark",
        "DJ": "Djibouti",
        "DM": "Dominica",
        "DO": "Dominican Republic",
        "EC": "Ecuador",
        "EG": "Egypt",
        "SV": "El Salvador",
        "GQ": "Equatorial Guinea",
        "ER": "Eritrea",
        "EE": "Estonia",
        "SZ": "Eswatini",
        "ET": "Ethiopia",
        "FK": "Falkland Islands",
        "FO": "Faroe Islands",
        "FJ": "Fiji",
        "FI": "Finland",
        "FR": "France",
        "GF": "French Guiana",
        "PF": "French Polynesia",
        "TF": "French Southern Territories",
        "GA": "Gabon",
        "GM": "Gambia",
        "GE": "Georgia",
        "DE": "Germany",
        "GH": "Ghana",
        "GI": "Gibraltar",
        "GR": "Greece",
        "GL": "Greenland",
        "GD": "Grenada",
        "GP": "Guadeloupe",
        "GU": "Guam",
        "GT": "Guatemala",
        "GG": "Guernsey",
        "GN": "Guinea",
        "GW": "Guinea-Bissau",
        "GY": "Guyana",
        "HT": "Haiti",
        "HM": "Heard Island and McDonald Islands",
        "VA": "Holy See",
        "HN": "Honduras",
        "HK": "Hong Kong",
        "HU": "Hungary",
        "IS": "Iceland",
        "IN": "India",
        "ID": "Indonesia",
        "IR": "Iran",
        "IQ": "Iraq",
        "IE": "Ireland",
        "IM": "Isle of Man",
        "IL": "Israel",
        "IT": "Italy",
        "JM": "Jamaica",
        "JP": "Japan",
        "JE": "Jersey",
        "JO": "Jordan",
        "KZ": "Kazakhstan",
        "KE": "Kenya",
        "KI": "Kiribati",
        "KP": "North Korea",
        "KR": "South Korea",
        "KW": "Kuwait",
        "KG": "Kyrgyzstan",
        "LA": "Lao PDR",
        "LV": "Latvia",
        "LB": "Lebanon",
        "LS": "Lesotho",
        "LR": "Liberia",
        "LY": "Libya",
        "LI": "Liechtenstein",
        "LT": "Lithuania",
        "LU": "Luxembourg",
        "MO": "Macao",
        "MG": "Madagascar",
        "MW": "Malawi",
        "MY": "Malaysia",
        "MV": "Maldives",
        "ML": "Mali",
        "MT": "Malta",
        "MH": "Marshall Islands",
        "MQ": "Martinique",
        "MR": "Mauritania",
        "MU": "Mauritius",
        "YT": "Mayotte",
        "MX": "Mexico",
        "FM": "Micronesia",
        "MD": "Moldova",
        "MC": "Monaco",
        "MN": "Mongolia",
        "ME": "Montenegro",
        "MS": "Montserrat",
        "MA": "Morocco",
        "MZ": "Mozambique",
        "MM": "Myanmar",
        "NA": "Namibia",
        "NR": "Nauru",
        "NP": "Nepal",
        "NL": "Netherlands",
        "NC": "New Caledonia",
        "NZ": "New Zealand",
        "NI": "Nicaragua",
        "NE": "Niger",
        "NG": "Nigeria",
        "NU": "Niue",
        "NF": "Norfolk Island",
        "MK": "North Macedonia",
        "MP": "Northern Mariana Islands",
        "NO": "Norway",
        "OM": "Oman",
        "PK": "Pakistan",
        "PW": "Palau",
        "PS": "Palestinian Territory",
        "PA": "Panama",
        "PG": "Papua New Guinea",
        "PY": "Paraguay",
        "PE": "Peru",
        "PH": "Philippines",
        "PN": "Pitcairn",
        "PL": "Poland",
        "PT": "Portugal",
        "PR": "Puerto Rico",
        "QA": "Qatar",
        "RE": "Réunion",
        "RO": "Romania",
        "RU": "Russia",
        "RW": "Rwanda",
        "BL": "Saint Barthélemy",
        "SH": "Saint Helena",
        "KN": "Saint Kitts and Nevis",
        "LC": "Saint Lucia",
        "MF": "Saint Martin (French part)",
        "PM": "Saint Pierre and Miquelon",
        "VC": "Saint Vincent and the Grenadines",
        "WS": "Samoa",
        "SM": "San Marino",
        "ST": "Sao Tome and Principe",
        "SA": "Saudi Arabia",
        "SN": "Senegal",
        "RS": "Serbia",
        "SC": "Seychelles",
        "SL": "Sierra Leone",
        "SG": "Singapore",
        "SX": "Sint Maarten",
        "SK": "Slovakia",
        "SI": "Slovenia",
        "SB": "Solomon Islands",
        "SO": "Somalia",
        "ZA": "South Africa",
        "GS": "South Georgia and the South Sandwich Islands",
        "SS": "South Sudan",
        "ES": "Spain",
        "LK": "Sri Lanka",
        "SD": "Sudan",
        "SR": "Suriname",
        "SJ": "Svalbard and Jan Mayen",
        "SE": "Sweden",
        "CH": "Switzerland",
        "SY": "Syrian Arab Republic",
        "TW": "Taiwan",
        "TJ": "Tajikistan",
        "TZ": "Tanzania",
        "TH": "Thailand",
        "TL": "Timor-Leste",
        "TG": "Togo",
        "TK": "Tokelau",
        "TO": "Tonga",
        "TT": "Trinidad and Tobago",
        "TN": "Tunisia",
        "TR": "Turkey",
        "TM": "Turkmenistan",
        "TC": "Turks and Caicos Islands",
        "TV": "Tuvalu",
        "UG": "Uganda",
        "UA": "Ukraine",
        "AE": "United Arab Emirates",
        "GB": "United Kingdom",
        "US": "United States",
        "UM": "United States Minor Outlying Islands",
        "UY": "Uruguay",
        "UZ": "Uzbekistan",
        "VU": "Vanuatu",
        "VE": "Venezuela",
        "VN": "Vietnam",
        "VG": "Virgin Islands, British",
        "VI": "Virgin Islands, U.S.",
        "WF": "Wallis and Futuna",
        "EH": "Western Sahara",
        "YE": "Yemen",
        "ZM": "Zambia",
        "ZW": "Zimbabwe"
    }
    @staticmethod
    def get_country_name(code):
        """
        Retrieve the full country name based on the country code.
        """
        return UserRegionGenerator.countries.get(code, "Unknown Region")